spring:
  application:
    name: car-workflow-cloud-app
    custom:
      config:
        taskService: api # api or repo
  #main:
  #  allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        # Where the Spring boot admin resides
        url: http://localhost:8100
        # When shut down deregisters from spring boot admin
        auto-deregistration: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: bfdeeb6ab61832622378
            clientSecret: 4a4fd7fc2620cce7eeedfb29205fcc95bbe14875
    custom:
      config:
        type: SECURE #SECURE or NONE
        secureWhitelist:
          # // -- Swagger UI v2
          - /v2/api-docs
          - v2/api-docs
          - /swagger-resources
          - swagger-resources
          - /swagger-resources/**
          - swagger-resources/**
          - /configuration/ui
          - configuration/ui
          - /configuration/security
          - configuration/security
          - /swagger-ui.html
          - swagger-ui.html
          - webjars/**,
          # // -- Swagger UI v3
          - /v3/api-docs/**
          - v3/api-docs/**
          - /swagger-ui/**
          - swagger-ui/**
          # // CSA Controllers
          - /csa/api/token
          # // Actuators
          - /actuator/**
          - /health/**
          # // Camunda
          - /carworkflowcloud/**
server:
  # Allow for automatic available port allocation
  port: 19000
  error:
    # e.g. when an 500 error is displayed will have the underlying error message
    include-message: always
zeebe:
  client:
    cloud:
      # Cluster URL: e.g. 68446f73-e278-44a3-b676-04592b9bc0d3.ont-1.zeebe.camunda.io
      region: ont-1
      clusterId: a2ee79e4-86de-4c37-be56-25ab6122770e
      clientId: 9ixeNYH5StdPwfWoEVeW1KxiNtUBpocl
      clientSecret: s-tJMZVWVQ6VDGahfnrTJ6Gfy4I-vQDKLPLVejuHWCYMIuO_tQcOqS6d9FsV32Zr
      oAuthUrl: https://login.cloud.camunda.io/oauth/token
    api:
      taskSearchUrl: https://${zeebe.client.cloud.region}.tasklist.camunda.io/${zeebe.client.cloud.clusterId}/v1/tasks/search
logging:
  level:
    org.springframework.security: INFO
  file:
    name: car-workflow-cloud-app.log
    max-history: 5
    max-size: 10MB
management:
  endpoint:
    env:
      # show the values in actuator/env endpoint
      # e.g. http://localhost:8101/actuator/env
      show-values: ALWAYS
    configprops:
      # show the values in actuator/configprops endpoint
      # e.g. http://localhost:8101/actuator/configprops
      show-values: ALWAYS
    health:
      # Note show-details
      show-details: ALWAYS
    shutdown:
      enabled: true
  endpoints:
    enabledByDefault: true
    env:
      # mask these values in actuator/env endpoint
      keys-to-sanitize: password,secret
    configprops:
      # mask these values in actuator/configprops endpoint
      keys-to-sanitize: password,secret
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      # All the GIT info
      mode: full
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
